version: '3'

services:
  jekyll:
    image: jekyll/jekyll:${JEKYLL_VERSION}
    ports:
      - 4000:4000
    volumes:
      - ./${PROJECT_DIR}:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    command: jekyll serve --watch --force_polling
