version: "3"

# Build and serve Jekyll app from current directory.
# `docker-compose up -d` starts the process. View at http://localhost:4000
# `docker-compose down` stops the process.
services:
  jekyll:
    image: jekyll/jekyll:${JEKYLL_VERSION}
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    command: jekyll serve --watch --force_polling
