version: '3'

services:
  jekyll:
    image: jekyll/jekyll:${JEKYLL_VERSION}
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    command: jekyll new ${PROJECT_DIR}
